### ISSUE TITLE
Add Heap Sort in Sorting Algorihms

### ISSUE THREAD

**Issue by yaswanthreddyyyr** [Anisha7860/Hacktoberfest_2022#14]
want to add Heap Sort Algorithm in Searching and Sorting Folder.

**Comment by Anisha7860** [comment]
Yep , go ahead

**Comment by yaswanthreddyyyr** [comment]
Hi @Anisha7860 
Created the pull request for the above issue .Please Merge it.

**Comment by Anisha7860** [comment]
Done.
